// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 23 Oct 2019 15:32:48 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "include/test.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

