// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 23 Oct 2019 15:32:48 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package wpi

/*
#cgo LDFLAGS: -Llib -lwpiHal -lwpilibc -lwpiutil -lstdc++
#include "include/test.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
